version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID: mavenS3RepoAccessKeyId
    AWS_SECRET_KEY: mavenS3RepoSecretKey
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - mvn deploy
      - echo Build completed on `date`
artifacts:
  files:
    - target/continuousdelivery-java-reference.jar
