version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - mvn deploy
      - echo Build completed on `date`
artifacts:
  files:
    - target/continuousdelivery-java-reference.jar
